logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 192.168.208.124 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: hmall
    password: 123
    virtual-host: /hmall
    listener:
      simple:
        prefetch: 1
    publisher-confirm-type: correlated
    publisher-returns: true