spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatisdemo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.208.124
    password: leadnews
    port: 6379
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
mybatis-plus:
  type-aliases-package: org.example.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted # 配置逻辑删除字段
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler